# fly.toml app configuration file generated for moonbot on 2024-09-28T01:10:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moonbot'
primary_region = 'gru'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
